import { Link } from 'react-router-dom';
import { ArrowDown, ArrowUpRight, MapPin } from 'lucide-react';
import { motion } from 'framer-motion';
import { BookingBand, InternalLink, PageMeta, SectionTitle } from '../components/PageParts';
import { resort } from '../data/siteData';
import { reveal } from '../data/motion';

export default function HomePage() {
  return <>
    <PageMeta title="Beachfront Resort" description="Stay directly on Ashwem Beach at Anahata Retreat, North Goa: palm-thatched cottages, Goan-style bungalows, L’Atelier dining, yoga and wellness." path="/" />
    <section className="home-hero"><motion.img initial={{ scale: 1.08 }} animate={{ scale: 1 }} transition={{ duration: 2 }} src="/images/anahata-hero.webp" alt="Anahata Retreat beside palm-fringed Ashwem Beach" fetchPriority="high" /><div className="home-hero-shade" /><motion.div className="home-hero-copy" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: .2, duration: 1 }}><p className="eyebrow eyebrow-light">Beachfront · Ashwem · North Goa</p><h1>Where the day<br />begins with <em>the sea.</em></h1><p>A soulful retreat of palm-thatched cottages, nourishing food and morning yoga, set directly on the quiet sands of Ashwem.</p><div className="hero-actions"><a className="button button-coral" href={resort.booking} target="_blank" rel="noreferrer">Book your stay <ArrowUpRight size={16} /></a><Link to="/experience">Discover Anahata <ArrowDown size={15} /></Link></div></motion.div><span className="hero-location">15.6449° N · 73.7179° E</span></section>

    <div className="fact-strip"><span>Direct beach access</span><span>Morning yoga</span><span>Retreats since 2012</span></div>

    <section className="home-story content-section"><motion.div {...reveal}><SectionTitle eyebrow="A retreat in the truest sense">Come as you are.<br /><em>Leave a little lighter.</em></SectionTitle></motion.div><motion.div {...reveal} className="home-story-copy"><p className="lead">Founded by Rishal and Angela in 2012, Anahata grew from a simple idea: create a warm place where people can return to nature and themselves.</p><p>Life here follows the shoreline. Wake with the light, wander barefoot to breakfast, swim when the sea calls and let evening unfold beneath the palms.</p><InternalLink to="/experience">Our story</InternalLink></motion.div><motion.figure {...reveal}><img src="/images/anahata-resort.webp" alt="Anahata Retreat nestled in a tropical garden" loading="lazy" /><figcaption>Between tropical garden and Arabian Sea</figcaption></motion.figure></section>

    <section className="home-stay content-section muted-section"><div className="split-heading"><SectionTitle eyebrow="Sleep by the sea">A space for every<br /><em>kind of quiet.</em></SectionTitle><p>Choose the natural ease of a palm-thatched cottage or the character of a Goan-Portuguese bungalow. Every stay keeps the beach close.</p></div><div className="feature-pair"><motion.article {...reveal}><Link to="/stay/cottages"><img src="/images/anahata-cottage.webp" alt="Palm-thatched cottage at Anahata" loading="lazy" /></Link><p className="card-kicker">Wooden cabanas · Sea and garden outlooks</p><h3>Cottages</h3><p>Raised on stilts beneath palm-thatched roofs, with a private balcony or veranda.</p><InternalLink to="/stay/cottages">Explore cottages</InternalLink></motion.article><motion.article {...reveal}><Link to="/stay/bungalows"><img src="/images/anahata-bungalow.webp" alt="Goan-style bungalow at Anahata" loading="lazy" /></Link><p className="card-kicker">Tiled roofs · Private verandas</p><h3>Bungalows</h3><p>Goan-Portuguese character, cooling shade and sea, partial-sea or garden settings.</p><InternalLink to="/stay/bungalows">Explore bungalows</InternalLink></motion.article></div><div className="center-link"><InternalLink to="/stay">Compare all stays</InternalLink></div></section>

    <section className="home-dining"><div><img src="/images/anahata-dining.webp" alt="Fresh food served at L’Atelier" loading="lazy" /></div><motion.div {...reveal}><SectionTitle eyebrow="L’Atelier · Beachfront dining" light>Food with a<br /><em>Goan soul.</em></SectionTitle><p>Local recipes, international favourites, fresh juices, house-baked bread and colourful plant-led plates, served with the Arabian Sea in view.</p><InternalLink to="/dining" light>Discover L’Atelier</InternalLink></motion.div></section>

    <section className="home-wellness content-section"><motion.div {...reveal}><SectionTitle eyebrow="Return to your rhythm">Move. Breathe.<br /><em>Feel alive.</em></SectionTitle><p className="lead">Practice above the tide, find stillness through meditation, or settle into a restorative treatment.</p><p>Morning yoga runs Monday to Saturday and is complimentary for in-house guests. Retreat leaders can bring their communities for a stay shaped around practice, food and connection.</p><div className="link-row"><InternalLink to="/yoga-wellness">Yoga & wellness</InternalLink><InternalLink to="/retreats">Host a retreat</InternalLink></div></motion.div><div className="portrait-collage"><img src="/images/anahata-yoga.webp" alt="Yoga overlooking Ashwem Beach" loading="lazy" /><img src="/images/anahata-wellness.webp" alt="Wellness treatment at Anahata" loading="lazy" /></div></section>

    <section className="home-location"><div className="mini-map"><iframe title="Anahata Retreat location on Google Maps" src="https://www.google.com/maps?q=15.6449687,73.7178535&z=16&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /></div><motion.div {...reveal}><SectionTitle eyebrow="Find your way to quiet">On Ashwem Beach,<br /><em>North Goa.</em></SectionTitle><p>Beside Ajoba Temple in Mandrem, the garden opens directly to one of North Goa’s calmest stretches of sand.</p><a className="button button-green" href={resort.maps} target="_blank" rel="noreferrer"><MapPin size={16} /> Open Google Maps</a></motion.div></section>
    <BookingBand />
  </>;
}
